export {MainPage} from './mainPage/mainPage'
export {LogIn} from './logIn/logIn'
export {Header} from './header/header'
export {Footer} from './footer/footer'
export {Registration} from './registration/registration'
export {AddTestPage} from './addTest/addTestPage'
export {AsideBar} from './asideBar/asideBar'
export {AddQuestionModal} from './addQuestion/addQuestion'
export {AddCoursePage} from './addCourse/addCoursePage'
export {CoursesList} from './coursesList/coursesList'
export {TestsList} from './testsList/testsList'

//export BannerImage from '../assets/images/test.png'