export const FETCH_TESTS = 'TESTS/FETCH_TESTS';
export const LOADING_TESTS_STARTED = 'TESTS/LOADING_STARTED';
export const LOADING_TESTS_SUCCESS = 'TESTS/LOADING_FINISHED';
export const LOADING_TESTS_FAILED = 'TESTS/LOADING_FAILED';

export const CREATE_TEST = 'TESTS/CREATE_TEST';
export const CREATING_TEST_STARTED = 'TESTS/CREATING_STARTED';
export const CREATING_TEST_SUCCESS ='TESTS/CREATING_FINISHED';
export const CREATING_TEST_FAILED = 'TESTS/CREATING_FAILED';

export const EDIT_COURSE = 'COURSES/EDIT_COURSE';
export const EDITING_COURSE_STARTED = 'COURSES/EDITING_STARTED';
export const EDITING_COURSE_SUCCESS = 'COURSES/EDITING_FINISHED';
export const EDITING_COURSE_FAILED = 'COURSES/EDITING_FAILED';

export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
export const DELETING_COURSE_STARTED = 'COURSES/DELETING_STARTED';
export const DELETING_COURSE_SUCCESS = 'COURSES/DELETING_FINISHED';
export const DELETING_COURSE_FAILED = 'COURSES/DELETING_FAILED';

export const CLEAR_LOADED = 'COURSES/CLEAR_LOADED';
export const CLEAR_ERROR = 'COURSES/CLEAR_ERROR';

export const ADD_TEST = 'TESTS/ADD_TEST';

export const GET_TEST_FOR_PASS = 'TEST/GET_TEST_FOR_PASS';
export const LOADING_TEST_FOR_PASS_STARTED= 'TEST/LOADING_TEST_FOR_PASS_STARTED';
export const LOADING_TEST_FOR_PASS_FINISHED= 'TEST/LOADING_TEST_FOR_PASS_FINISHED';
export const LOADING_TEST_FOR_PASS_FAILED= 'TEST/LOADING_TEST_FOR_PASS_FAILED';
