export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER = 'CLEAR_USER';

export const REGIST_REQUSTING = 'REGIST_REQUSTING';
export const REGIST_STARTED = 'REGIST_STARTED';
export const REGIST_SUCCESS = 'REGIST_SUCCESS';
export const REGIST_ERROR = 'REGIST_ERROR';

export const CLEAR_LOADED = 'CLEAR_REGISTRATION';
