export const CREATE_QUESTION = 'QUESTIONS/CREATE_QUESTION';
export const REMOVE_QUESTION = 'QUESTIONS/REMOVE_QUESTION';
export const CLEAR_QUESTIONS = 'QUESTIONS/CLEAR_QUESTIONS';
export const EDIT_QUESTION = 'QUESTIONS/EDIT_QUESTION';